/* World Cup 2026 Auction — player pool.
 *
 * A curated pool of well-known players from nations at the 2026 World Cup.
 * Ratings (OVR) are gameplay values only, not official statistics.
 * Format: [name, nationCode, position, ovr]  pos: GK | DEF | MID | FWD
 * Edit freely — the game reads this file at load.
 */

const NATIONS = {
  ARG: { flag: '\u{1F1E6}\u{1F1F7}', en: 'Argentina',      ar: 'الأرجنتين' },
  BRA: { flag: '\u{1F1E7}\u{1F1F7}', en: 'Brazil',         ar: 'البرازيل' },
  FRA: { flag: '\u{1F1EB}\u{1F1F7}', en: 'France',         ar: 'فرنسا' },
  ENG: { flag: '\u{1F3F4}\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}', en: 'England', ar: 'إنجلترا' },
  ESP: { flag: '\u{1F1EA}\u{1F1F8}', en: 'Spain',          ar: 'إسبانيا' },
  POR: { flag: '\u{1F1F5}\u{1F1F9}', en: 'Portugal',       ar: 'البرتغال' },
  NED: { flag: '\u{1F1F3}\u{1F1F1}', en: 'Netherlands',    ar: 'هولندا' },
  GER: { flag: '\u{1F1E9}\u{1F1EA}', en: 'Germany',        ar: 'ألمانيا' },
  BEL: { flag: '\u{1F1E7}\u{1F1EA}', en: 'Belgium',        ar: 'بلجيكا' },
  CRO: { flag: '\u{1F1ED}\u{1F1F7}', en: 'Croatia',        ar: 'كرواتيا' },
  URU: { flag: '\u{1F1FA}\u{1F1FE}', en: 'Uruguay',        ar: 'أوروغواي' },
  COL: { flag: '\u{1F1E8}\u{1F1F4}', en: 'Colombia',       ar: 'كولومبيا' },
  MAR: { flag: '\u{1F1F2}\u{1F1E6}', en: 'Morocco',        ar: 'المغرب' },
  EGY: { flag: '\u{1F1EA}\u{1F1EC}', en: 'Egypt',          ar: 'مصر' },
  SEN: { flag: '\u{1F1F8}\u{1F1F3}', en: 'Senegal',        ar: 'السنغال' },
  JPN: { flag: '\u{1F1EF}\u{1F1F5}', en: 'Japan',          ar: 'اليابان' },
  KOR: { flag: '\u{1F1F0}\u{1F1F7}', en: 'South Korea',    ar: 'كوريا الجنوبية' },
  USA: { flag: '\u{1F1FA}\u{1F1F8}', en: 'United States',  ar: 'الولايات المتحدة' },
  MEX: { flag: '\u{1F1F2}\u{1F1FD}', en: 'Mexico',         ar: 'المكسيك' },
  CAN: { flag: '\u{1F1E8}\u{1F1E6}', en: 'Canada',         ar: 'كندا' },
  NOR: { flag: '\u{1F1F3}\u{1F1F4}', en: 'Norway',         ar: 'النرويج' },
  POL: { flag: '\u{1F1F5}\u{1F1F1}', en: 'Poland',         ar: 'بولندا' },
  SUI: { flag: '\u{1F1E8}\u{1F1ED}', en: 'Switzerland',    ar: 'سويسرا' },
  AUS: { flag: '\u{1F1E6}\u{1F1FA}', en: 'Australia',      ar: 'أستراليا' },
  IRN: { flag: '\u{1F1EE}\u{1F1F7}', en: 'Iran',           ar: 'إيران' },
  KSA: { flag: '\u{1F1F8}\u{1F1E6}', en: 'Saudi Arabia',   ar: 'السعودية' },
  QAT: { flag: '\u{1F1F6}\u{1F1E6}', en: 'Qatar',          ar: 'قطر' },
  JOR: { flag: '\u{1F1EF}\u{1F1F4}', en: 'Jordan',         ar: 'الأردن' },
  UZB: { flag: '\u{1F1FA}\u{1F1FF}', en: 'Uzbekistan',     ar: 'أوزبكستان' },
  ECU: { flag: '\u{1F1EA}\u{1F1E8}', en: 'Ecuador',        ar: 'الإكوادور' },
  PAR: { flag: '\u{1F1F5}\u{1F1FE}', en: 'Paraguay',       ar: 'باراغواي' },
  ALG: { flag: '\u{1F1E9}\u{1F1FF}', en: 'Algeria',        ar: 'الجزائر' },
  TUN: { flag: '\u{1F1F9}\u{1F1F3}', en: 'Tunisia',        ar: 'تونس' },
  CIV: { flag: '\u{1F1E8}\u{1F1EE}', en: 'Ivory Coast',    ar: 'ساحل العاج' },
  GHA: { flag: '\u{1F1EC}\u{1F1ED}', en: 'Ghana',          ar: 'غانا' },
};

const POOL_RAW = [
  // ---- Goalkeepers ----
  ['Emiliano Martínez', 'ARG', 'GK', 88],
  ['Alisson Becker', 'BRA', 'GK', 88],
  ['Ederson', 'BRA', 'GK', 85],
  ['Mike Maignan', 'FRA', 'GK', 88],
  ['Thibaut Courtois', 'BEL', 'GK', 90],
  ['Jordan Pickford', 'ENG', 'GK', 84],
  ['Unai Simón', 'ESP', 'GK', 84],
  ['Diogo Costa', 'POR', 'GK', 85],
  ['Marc-André ter Stegen', 'GER', 'GK', 86],
  ['Bart Verbruggen', 'NED', 'GK', 82],
  ['Dominik Livaković', 'CRO', 'GK', 82],
  ['Yassine Bounou', 'MAR', 'GK', 86],
  ['Édouard Mendy', 'SEN', 'GK', 82],
  ['Zion Suzuki', 'JPN', 'GK', 81],
  ['Jo Hyeon-woo', 'KOR', 'GK', 79],
  ['Matt Turner', 'USA', 'GK', 78],
  ['Luis Malagón', 'MEX', 'GK', 80],
  ['Maxime Crepeau', 'CAN', 'GK', 76],
  ['Mathew Ryan', 'AUS', 'GK', 78],
  ['Mohamed El Shenawy', 'EGY', 'GK', 79],
  ['Raïs M’Bolhi', 'ALG', 'GK', 76],
  ['Yassine Bounou', 'MAR', 'GK', 86],

  // ---- Defenders ----
  ['Virgil van Dijk', 'NED', 'DEF', 89],
  ['Achraf Hakimi', 'MAR', 'DEF', 88],
  ['Rúben Dias', 'POR', 'DEF', 88],
  ['William Saliba', 'FRA', 'DEF', 87],
  ['Cristian Romero', 'ARG', 'DEF', 87],
  ['Gabriel Magalhães', 'BRA', 'DEF', 87],
  ['Joško Gvardiol', 'CRO', 'DEF', 86],
  ['Alphonso Davies', 'CAN', 'DEF', 86],
  ['Trent Alexander-Arnold', 'ENG', 'DEF', 86],
  ['Antonio Rüdiger', 'GER', 'DEF', 85],
  ['Jules Koundé', 'FRA', 'DEF', 85],
  ['Marquinhos', 'BRA', 'DEF', 85],
  ['Éder Militão', 'BRA', 'DEF', 85],
  ['Dani Carvajal', 'ESP', 'DEF', 85],
  ['Ronald Araújo', 'URU', 'DEF', 85],
  ['Kim Min-jae', 'KOR', 'DEF', 85],
  ['Theo Hernández', 'FRA', 'DEF', 84],
  ['Marc Cucurella', 'ESP', 'DEF', 84],
  ['Jurriën Timber', 'NED', 'DEF', 84],
  ['Micky van de Ven', 'NED', 'DEF', 84],
  ['John Stones', 'ENG', 'DEF', 84],
  ['José María Giménez', 'URU', 'DEF', 84],
  ['Pau Cubarsí', 'ESP', 'DEF', 84],
  ['Dean Huijsen', 'ESP', 'DEF', 83],
  ['Piero Hincapié', 'ECU', 'DEF', 83],
  ['Nathan Aké', 'NED', 'DEF', 83],
  ['Nicolás Otamendi', 'ARG', 'DEF', 82],
  ['Nayef Aguerd', 'MAR', 'DEF', 82],
  ['Kalidou Koulibaly', 'SEN', 'DEF', 82],
  ['Davinson Sánchez', 'COL', 'DEF', 81],
  ['Evan Ndicka', 'CIV', 'DEF', 80],
  ['Sergiño Dest', 'USA', 'DEF', 80],
  ['Chris Richards', 'USA', 'DEF', 79],
  ['Johan Vásquez', 'MEX', 'DEF', 79],
  ['Takehiro Tomiyasu', 'JPN', 'DEF', 79],
  ['Jan Bednarek', 'POL', 'DEF', 78],
  ['Manuel Akanji', 'SUI', 'DEF', 83],
  ['Jesús Gallardo', 'MEX', 'DEF', 77],
  ['Moataz Zemzemi', 'TUN', 'DEF', 76],
  ['Ahmed Hegazi', 'EGY', 'DEF', 77],
  ['Aissa Mandi', 'ALG', 'DEF', 79],
  ['Harry Souttar', 'AUS', 'DEF', 77],
  ['Majid Hosseini', 'IRN', 'DEF', 76],

  // ---- Midfielders ----
  ['Rodri', 'ESP', 'MID', 91],
  ['Jude Bellingham', 'ENG', 'MID', 90],
  ['Pedri', 'ESP', 'MID', 90],
  ['Jamal Musiala', 'GER', 'MID', 89],
  ['Florian Wirtz', 'GER', 'MID', 89],
  ['Federico Valverde', 'URU', 'MID', 89],
  ['Declan Rice', 'ENG', 'MID', 88],
  ['Joshua Kimmich', 'GER', 'MID', 88],
  ['Bruno Fernandes', 'POR', 'MID', 88],
  ['Vitinha', 'POR', 'MID', 88],
  ['Kevin De Bruyne', 'BEL', 'MID', 88],
  ['Alexis Mac Allister', 'ARG', 'MID', 87],
  ['Bernardo Silva', 'POR', 'MID', 87],
  ['Moisés Caicedo', 'ECU', 'MID', 87],
  ['Cole Palmer', 'ENG', 'MID', 87],
  ['Enzo Fernández', 'ARG', 'MID', 86],
  ['Frenkie de Jong', 'NED', 'MID', 86],
  ['Luka Modrić', 'CRO', 'MID', 85],
  ['Aurélien Tchouaméni', 'FRA', 'MID', 85],
  ['Ryan Gravenberch', 'NED', 'MID', 85],
  ['Bruno Guimarães', 'BRA', 'MID', 85],
  ['Mohammed Kudus', 'GHA', 'MID', 85],
  ['Gavi', 'ESP', 'MID', 85],
  ['Eduardo Camavinga', 'FRA', 'MID', 84],
  ['Rodrigo De Paul', 'ARG', 'MID', 84],
  ['Youri Tielemans', 'BEL', 'MID', 84],
  ['Granit Xhaka', 'SUI', 'MID', 84],
  ['Takefusa Kubo', 'JPN', 'MID', 83],
  ['Pape Matar Sarr', 'SEN', 'MID', 82],
  ['Warren Zaïre-Emery', 'FRA', 'MID', 82],
  ['Edson Álvarez', 'MEX', 'MID', 82],
  ['James Rodríguez', 'COL', 'MID', 82],
  ['Piotr Zieliński', 'POL', 'MID', 82],
  ['Thomas Partey', 'GHA', 'MID', 82],
  ['Franck Kessié', 'CIV', 'MID', 82],
  ['Lee Kang-in', 'KOR', 'MID', 82],
  ['Ismaël Bennacer', 'ALG', 'MID', 81],
  ['Daichi Kamada', 'JPN', 'MID', 80],
  ['Sofyan Amrabat', 'MAR', 'MID', 80],
  ['Weston McKennie', 'USA', 'MID', 80],
  ['Tyler Adams', 'USA', 'MID', 79],
  ['Azzedine Ounahi', 'MAR', 'MID', 78],
  ['Miguel Almirón', 'PAR', 'MID', 78],
  ['Stephen Eustáquio', 'CAN', 'MID', 78],
  ['Aïssa Laïdouni', 'TUN', 'MID', 77],
  ['Hannibal Mejbri', 'TUN', 'MID', 76],
  ['Mohamed Elneny', 'EGY', 'MID', 76],
  ['Jackson Irvine', 'AUS', 'MID', 76],
  ['Saeid Ezatolahi', 'IRN', 'MID', 76],
  ['Jasurbek Jaloliddinov', 'UZB', 'MID', 75],
  ['Nour Al-Rawabdeh', 'JOR', 'MID', 76],
  ['Salem Al-Dawsari', 'KSA', 'MID', 80],

  // ---- Forwards ----
  ['Kylian Mbappé', 'FRA', 'FWD', 93],
  ['Erling Haaland', 'NOR', 'FWD', 92],
  ['Lamine Yamal', 'ESP', 'FWD', 91],
  ['Lionel Messi', 'ARG', 'FWD', 90],
  ['Vinícius Júnior', 'BRA', 'FWD', 90],
  ['Harry Kane', 'ENG', 'FWD', 90],
  ['Raphinha', 'BRA', 'FWD', 89],
  ['Ousmane Dembélé', 'FRA', 'FWD', 89],
  ['Mohamed Salah', 'EGY', 'FWD', 89],
  ['Julián Álvarez', 'ARG', 'FWD', 88],
  ['Bukayo Saka', 'ENG', 'FWD', 88],
  ['Luis Díaz', 'COL', 'FWD', 88],
  ['Lautaro Martínez', 'ARG', 'FWD', 87],
  ['Nico Williams', 'ESP', 'FWD', 87],
  ['Michael Olise', 'FRA', 'FWD', 87],
  ['Son Heung-min', 'KOR', 'FWD', 86],
  ['Phil Foden', 'ENG', 'FWD', 86],
  ['Robert Lewandowski', 'POL', 'FWD', 86],
  ['Cristiano Ronaldo', 'POR', 'FWD', 85],
  ['Rafael Leão', 'POR', 'FWD', 85],
  ['Rodrygo', 'BRA', 'FWD', 85],
  ['Cody Gakpo', 'NED', 'FWD', 85],
  ['Christian Pulisic', 'USA', 'FWD', 85],
  ['Omar Marmoush', 'EGY', 'FWD', 84],
  ['Xavi Simons', 'NED', 'FWD', 84],
  ['Brahim Díaz', 'MAR', 'FWD', 84],
  ['Kaoru Mitoma', 'JPN', 'FWD', 84],
  ['Sadio Mané', 'SEN', 'FWD', 84],
  ['Riyad Mahrez', 'ALG', 'FWD', 84],
  ['Mehdi Taremi', 'IRN', 'FWD', 84],
  ['Romelu Lukaku', 'BEL', 'FWD', 84],
  ['Jérémy Doku', 'BEL', 'FWD', 84],
  ['Jonathan David', 'CAN', 'FWD', 84],
  ['Estêvão', 'BRA', 'FWD', 83],
  ['Bradley Barcola', 'FRA', 'FWD', 83],
  ['Marcus Rashford', 'ENG', 'FWD', 82],
  ['Darwin Núñez', 'URU', 'FWD', 82],
  ['Youssef En-Nesyri', 'MAR', 'FWD', 82],
  ['Ismaïla Sarr', 'SEN', 'FWD', 82],
  ['Antoine Semenyo', 'GHA', 'FWD', 82],
  ['Mikel Oyarzabal', 'ESP', 'FWD', 82],
  ['Santiago Giménez', 'MEX', 'FWD', 82],
  ['Hakim Ziyech', 'MAR', 'FWD', 80],
  ['Nicolas Jackson', 'SEN', 'FWD', 81],
  ['Amine Gouiri', 'ALG', 'FWD', 81],
  ['Ritsu Dōan', 'JPN', 'FWD', 81],
  ['Folarin Balogun', 'USA', 'FWD', 80],
  ['Jhon Durán', 'COL', 'FWD', 80],
  ['Rasmus Højlund', 'NOR', 'FWD', 80],
  ['Musa Al-Taamari', 'JOR', 'FWD', 80],
  ['Sardar Azmoun', 'IRN', 'FWD', 80],
  ['João Félix', 'POR', 'FWD', 80],
  ['Julio Enciso', 'PAR', 'FWD', 79],
  ['Enner Valencia', 'ECU', 'FWD', 79],
  ['Simon Adingra', 'CIV', 'FWD', 79],
  ['Akram Afif', 'QAT', 'FWD', 79],
  ['Breel Embolo', 'SUI', 'FWD', 79],
  ['Eldor Shomurodov', 'UZB', 'FWD', 79],
  ['Hwang Hee-chan', 'KOR', 'FWD', 79],
  ['Hirving Lozano', 'MEX', 'FWD', 79],
  ['Ricardo Pepi', 'USA', 'FWD', 78],
  ['Cyle Larin', 'CAN', 'FWD', 78],
  ['Almoez Ali', 'QAT', 'FWD', 77],
  ['Yazan Al-Naimat', 'JOR', 'FWD', 77],
  ['Firas Al-Buraikan', 'KSA', 'FWD', 76],
  ['Mostafa Mohamed', 'EGY', 'FWD', 78],
];

// Deduplicate by name+nation, then attach ids and base prices.
const PLAYERS = (function () {
  const seen = new Set();
  const out = [];
  POOL_RAW.forEach(function (row) {
    const key = row[0] + '|' + row[1];
    if (seen.has(key)) return;
    seen.add(key);
    out.push({
      id: 'p' + out.length,
      name: row[0],
      nat: row[1],
      pos: row[2],
      ovr: row[3],
      base: Math.max(1, Math.round((row[3] - 76) * 1.2)),
    });
  });
  return out;
})();

if (typeof window !== 'undefined') {
  window.NATIONS = NATIONS;
  window.PLAYERS = PLAYERS;
}
